@startuml

    ' Includes the sequence_diagram_stylesheet from a gist
    !include https://gist.githubusercontent.com/fishey2/7178a88643a8850908c799be1ec68fd6/raw/fc90505df1321e5c5022eab84d1e0b5044194d1c/example_sequence_stylesheet.iuml

    header Participants

    ' You can define participants with friendly names
    ' when you do this it makes it long to refer to it
    ' as you can see in the example below
    participant "Friendly Name 1"

    ' Instead we can define a friendly name and an alias
    ' This means we can refer to the participant in this script as second
    ' yet in the diagram it will appear as 'Friendly Name 2'
    participant "Friendly Name 2" as second

    ' This creates an arrow going from 'Friendly Name 1' and 'Friendly Name 2'
    "Friendly Name 1" -> second

@enduml