 @startuml

     ' Includes the sequence_diagram_stylesheet from a gist
     !include https://gist.githubusercontent.com/fishey2/7178a88643a8850908c799be1ec68fd6/raw/fc90505df1321e5c5022eab84d1e0b5044194d1c/example_sequence_stylesheet.iuml

     header Defining Lifelines

     ' First participant
     participant "Participant 1" as p1

     ' Second participant
     participant "Participant 2" as p2

     ' Third Participant
     database "Database" as db


    ' There are two ways to manage lifelines:
    '  * Using the 'activate', 'create', 'destroy' and 'deactivate' keywords
    '  * Using the shortcuts '++', '**', '!!' and 'return' symbols and keywords


    ' Activating and Deactivating

    ' Adds lifeline block to p2
    p1 -> p2
        activate p2

    ' Ends lifeline block on p2
    p2 -> p1
        deactivate p2

    ' Adds lifeline block to p2
    p1 -> p2 ++

    ' Ends lifeline block on p2
    p2 -> p1 --


    ' Creating and Destroying

    ' Creates a new participant p3 (doesn't appear with the rest at the top)
    create p3

    p1 -> p3
        ' return keyword can be used instead of '--'
        return

    ' Destroys the new participant p3
    ' Destroying puts a big cross on the lifeline of the object
    destroy p3

    ' Creates new participant called p4 (doesn't appear with the rest at the top)
    p1 -> p4 **

    ' It will add the cross on the end with the arrow
    p1 -> p4 !!

 @enduml