 @startuml

     ' Includes the sequence_diagram_stylesheet from a gist
     !include https://gist.githubusercontent.com/fishey2/7178a88643a8850908c799be1ec68fd6/raw/fc90505df1321e5c5022eab84d1e0b5044194d1c/example_sequence_stylesheet.iuml

     header Arrow Types

     ' First participant
     participant "Participant 1" as p1

     ' Second participant
     participant "Participant 2" as p2

     ' Third Participant
     database "Database" as db

    ' Adds lifeline block to p2
    p1 -> p2 ++

    ' Adds a second lifeline block to p2
    p2 -> p2 ++

    ' Adds lifeline
    p2 -> db ++

    ' Creates new
    db -> Object **

    ' return arrow
    return
    return

    ' Ends lifeline with X
    p2 -> Object !!
    return

 @enduml