@startuml

    ' Includes the sequence_diagram_stylesheet from a gist
    !include https://gist.githubusercontent.com/fishey2/7178a88643a8850908c799be1ec68fd6/raw/fc90505df1321e5c5022eab84d1e0b5044194d1c/example_sequence_stylesheet.iuml

    header Defining Arrows

    ' First participant
    participant "Participant 1" as p1

    ' Second participant
    participant "Participant 2" as p2



    ' Loopback arrow
    ' From Participant 1 to Participant 1
    p1 -> p1

    ' Left to right
    ' From Participant 1 to Participant 2
    p1 -> p2

    ' Right to left
    ' From Participant 2 to Participant 1
    p1 <- p2

    ' To left of page
    ' From Participant 2 to Page left
    [<- p2

    ' To right of page
    ' From Participant 1 to Page right
    p1 ->]

    ' From left of page
    ' From Page left to Participant 2
    [-> p2

    ' From right of page
    ' From Page right to Participant 1
    p1 <-]

@enduml